# SonarQube Cloud settings
sonar.organization=joinsrikanth945


# What to analyse
sonar.sources=app
sonar.tests=tests
sonar.python.version=3.11

# Test coverage report produced by pytest-cov in the pipeline
sonar.python.coverage.reportPaths=coverage.xml
sonar.projectKey=joinsrikanth945_Wealth-agentic-rag-azure-openai
sonar.projectName=Wealth Agentic RAG - Azure OpenAI
